// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuM9aK6sAJgeawq2s5MDijQt9nHiTkdJM',
    appId: '1:52411778490:web:2efb137c6c8567a4130983',
    messagingSenderId: '52411778490',
    projectId: 'bgtt-eeff9',
    authDomain: 'bgtt-eeff9.firebaseapp.com',
    storageBucket: 'bgtt-eeff9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxP-aQJK0rLWJmoOQW-24rxqpdWPie9zM',
    appId: '1:52411778490:android:dff5d614afe325d6130983',
    messagingSenderId: '52411778490',
    projectId: 'bgtt-eeff9',
    storageBucket: 'bgtt-eeff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm6Dkdxb8NZmuAGK5Gdbq_Ct29StoIeWc',
    appId: '1:52411778490:ios:0e33c32ee00af7ac130983',
    messagingSenderId: '52411778490',
    projectId: 'bgtt-eeff9',
    storageBucket: 'bgtt-eeff9.appspot.com',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm6Dkdxb8NZmuAGK5Gdbq_Ct29StoIeWc',
    appId: '1:52411778490:ios:0e33c32ee00af7ac130983',
    messagingSenderId: '52411778490',
    projectId: 'bgtt-eeff9',
    storageBucket: 'bgtt-eeff9.appspot.com',
    iosBundleId: 'com.example.bt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuM9aK6sAJgeawq2s5MDijQt9nHiTkdJM',
    appId: '1:52411778490:web:a4bf85253099c038130983',
    messagingSenderId: '52411778490',
    projectId: 'bgtt-eeff9',
    authDomain: 'bgtt-eeff9.firebaseapp.com',
    storageBucket: 'bgtt-eeff9.appspot.com',
  );

}